[package]
name = "twoderaycaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
noise = "0.8.2"
pixels = "0.13.0"
rayon = "1.7.0"
winit = "0.28.6"
winit_input_helper = "0.14.1"
